# Generated by Django 5.2.4 on 2025-07-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useractivity_recommendations_useractivity_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('recommendation', 'Recommendation'), ('upload', 'Resume Upload')], max_length=50),
        ),
    ]
