# Generated by Django 5.2.4 on 2025-07-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useractivity_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='resume',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('recommendation', 'Recommendation')], max_length=50),
        ),
    ]
